#!/usr/bin/env bash

echo "-- Welcome to Intercity Next"

# Run database migrations
echo "-- Setting up database"
bundle exec rake db:create

echo "-- Migrating app database"
bundle exec rake db:migrate

foreman start
